# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane
# FASTLANE_USER=<Apple USER ID>
# FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD=<App-Specific Password>

default_platform(:ios)

platform :ios do
  # before_all do
  #   FASTLANE_USER = "ios@cloudanalogy.com"
  #   FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD = "wtyr-ydsj-sjlf-gpsb"
  # end
  desc "Load ASC API Key information to use in subsequent lanes"
  lane :load_asc_api_key do
    app_store_connect_api_key(
      key_id: ENV["ASC_KEY_ID"],
      issuer_id: ENV["ASC_ISSUER_ID"],
      key_content: ENV["ASC_KEY"],
      is_key_content_base64: true,
      in_house: false # detecting this via ASC private key not currently supported
    )
  end

  desc "Build and upload to TestFlight"
   lane :build_upload_testflight do
     load_asc_api_key
     prepare_signing
     fetch_and_increment_build_number
     build_release
     upload_release
   end
   
  desc "Push a new beta build to TestFlight"
  lane :beta do
    # slack(message: "Build started")
    increment_build_number(xcodeproj: "rncicd_poc.xcodeproj")
    build_app(workspace: "rncicd_poc.xcworkspace", scheme: "rncicd_poc")
    upload_to_testflight
    # slack(message: "Successfully distributed a new beta build")
  end

  lane :release do
    # capture_screenshots                  # generate new screenshots for the App Store
    sync_code_signing(type: "appstore")  # see code signing guide for more information
    build_app(scheme: "rncicd_poc")
    upload_to_app_store                  # upload your app to App Store Connect
  end
end
