name: Merge into main branch

on:
  push:
    branches:
      - main

jobs:
  dummy-job:
    runs-on: ubuntu-latest
    steps:
      - name: Initilize job
        run: echo "Initilize job"

  # build-android:
  #   needs: install-and-test
  #   uses: ./.github/workflows/android-build.yml
  #   with:
  #     environment: release
  #   secrets: inherit

  build-ios:
    uses: ./.github/workflows/deploy-ios-prod.yml
    with:
      environment: release
    secrets: inherit
